= [StarTech] Compte rendu de la réunion du StarTech Java du 2017/01/03
:toc:
:toclevels: 3
:toc-placement!:
:lb: pass:[<br> +]
:imagesdir: images
:icons: font
:source-highlighter: highlightjs
:sectnums:

toc::[]

== Overview

Etaient inscrits :

* *Thomas SCHWENDER* : présent
* *Passam KASSEM* : présent
* *Guillaume LEMONT* : présent
* *Faycal TIRICH* : présent
* *Walid DEBBECH* : présent
* *Romain BEGHI* : présent
* *Soufiane KHATTAB* : présent
* *Nafia AMAZIANE* : présent
* *Bastien GIEGEL* : présent
* *BENDEBBA Nizar* : absent

== Logistique

* [red]*Trombinoscope* : +
Votre rappel préféré : envoyez une photo (où l’on vous reconnaît) et votre description, et je vous ajoute dans la foulée emoji:wink[2x]
* Afin de permettre au groupe d'être davantage connu des autres softeamiens, merci à *tous les contributeurs* de se créer une *signature* sur le modèle de la mienne (vous pouvez la prendre en copier / coller du présent mail)
* Tous les contributeurs doivent basculer sur le *NOUVEAU* channel Slack : https://startechs.slack.com/ +
Et, si vous pouviez, tous les jours en buvant votre café du matin, y jeter un oeil, voire vous mettre à troller, ce serait parfait ! emoji:wink[2x]
* Rappel : *les comptes-rendus de réunions* sont maintenant disponibles dans https://github.com/softeamfr/startech-meetings-reports[notre repo GitHub]. +
Ainsi, si vous avez des remarques, ou souhaitez apporter des modifications, vous pouvez : 
** soit utiliser https://github.com/softeamfr/startech-meetings-reports/issues[le bug tracker]
** soit soumettre une *pull request*.
* A partir de cette année, *la présence aux réunions mensuelles est récompensée de 40 Starpoints* !

== Tech

=== Divers et rappels

* mon sujet *Sorcellerie en Java : outrepasser les limites avec sun.misc.Unsafe* passera en quickie à Devoxx, suite à la victoire au Paris JUG du 10/01.
* réunion écourtée suite à pb de digicode

=== Questions, remarques & Co : 

* On ne passe plus par l'éditeur du blog, mais on link simplement un article écrit ailleurs (GitHub ou autre, en AsciiDoctor bien sûr ;) ) 

=== Veille technologique

* Faycal conseille Pocket pour lire des articles offline sur mobile (ex : dans le métro) +
Permet également de suivre les articles likés par une personne en particulier.

* Medium.com : bon site de veille, héberge de nombreux articles avec possibilité de suivre une personne en particulier. +
Possibilité de suivre des tags, mais ces derniers ne sont pas disponibles sous forme de flux RSS spécifiques.



=== Challenge de janvier

1 semaine de plus pour répondre !

==== Définitions proposées par les contributeurs

* *Guillaume LEMONT* : link:monad-definition/GLE_monade-kezako.adoc[ma tentative d'explication]
* *Bastien GIEGEL* : https://github.com/bgiegel/Definition_Monade/
* *Walid DEBBECH* : link:monad-definition/WDE_monade-chocolat.adoc[La monade, c'est du chocolat]
* *Thomas SCHWENDER* : link:monad-definition/TSC_monad-definition.adoc[Monade Kezako ?]

=== Projet de présentation sur Java 9

* Guillaume a souffert sur HTTP/2 qui est passé en fonctionnalité incubator suite à un retard par rapport au planning initial.

Rappel du dispatching des sujets à ce jour :

* *Jigsaw* : Guillaume + Passam + Abdoulaye + Thomas
* *HTTP/2* : Guillaume + Passam
* *Process API* : Thomas
* *REPL* : Soufiane + Thomas
* *Immutable collection factories* : Walid
* *HTML 5 Javadoc* : Soufiane
* *Garbage Collector G1* : Soufiane

On va essayer d'avancer les différents sujets pour mars.

repo spécifique pour la présentation : https://github.com/softeamfr/java9-presentation

Si vous êtes intéressés par rejoindre un groupe, [red]*n'hésitez pas à vous manifester sur notre https://startechjava.slack.com/messages/java9-presentation/[channel Slack dédié] !*

@+, +
Thomas
