= [StarTech] Compte rendu de la réunion du StarTech Java du 2018/12/04
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To turn off figure caption labels and numbers
//:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
:caption:

toc::[]

== Overview

Etaient présents :

* *Ahmed DAMMAK* : présent 
* *Aymen MAROUANI* : présent
* *Clarence CHARLES* : présent
* *Jérémie LOU* : présent
* *Manel BENYAHIA* : présent
* *Seifallah BENTEMESSEK* : présent
* *Thomas SCHWENDER* : présent
* *Yacine TRIAA* : présent		

== Tech

Nous avons refait le point sur la sortie de Java 11, et les évolutions en matière de license ayant eu lieu depuis Java 8, et tout particulièrement la notion de LTS (Long Term Support) +
A partir de Java 11, pour rester "gratuitement" sur le JDK d'Oracle *ET* continuer à bénéficier des mises à jour (de sécurité et autres patchs), il faudra se mettre à jour tous les 6 mois. +
S'il ne vous est pas possible de supporter le rythme de ses releases, mais que vous voulez continuer à rester à jour côté mises à jour, 2 solutions sont possibles :

* souscrire à l'offre de support d'Oracle
* passer à une implémentation d'OpenJDK d'un autre provider, comme Azul (payante également), IBM, Red Hat ou encore https://adoptopenjdk.net/[AdoptOpenJDK] (cette dernière ayant notre préférence).

Information toute récente à noter : Amazon, qui a embauché James Gosling (le créateur de Java), a sorti courant novembre sa propre implémetation d'OpenJDK, *Amazon Corretto*.

NOTE: Pour les intéressés, un https://fr.wikipedia.org/wiki/Caff%C3%A8_corretto[Corretto] est un café auquel on a ajouté de la liqueur. +
Java reste donc bien définitivement dans la thématique du café 

https://aws.amazon.com/fr/about-aws/whats-new/2018/11/introducing-amazon-corretto/

Quelques liens utiles sur le sujet :

* un très bon article sur Medium : https://medium.com/@javachampions/java-is-still-free-c02aef8c9e04[Java Is Still Free]
* https://docs.oracle.com/en/java/javase/11/migrate/index.html[le guide migration d'Oracle vers Java 11]
* https://aws.amazon.com/fr/about-aws/whats-new/2018/11/introducing-amazon-corretto/[L'annonce d'Amazon Corretto]





Amazon Corretto avec James Gosling
proposition avec support





Perf

GraalVM et ZeroGC

Service de paiement en ligne, du changement à venir


